### ISSUE TITLE
Failed to run clickhouse-server with clickhouse-jdbc-bridge-service  in docker-compose.

### ISSUE THREAD

**Issue by yoki123** [ClickHouse/clickhouse-jdbc-bridge#42]
This is my docker-compose.yml
```
version: "3"
services:
    clickhouse-server:
     image: yandex/clickhouse-server
     ports:
     - "8123:8123"
     - "9000:9000"
     - "9009:9009"

    clickhouse-jdbc-bridge:
        image: riftbit/clickhouse-jdbc-bridge-service
        ports:
          - '9019:9019'
       depends_on:
          - clickhouse-server
```

I put `clickhouse-server` and `clickhouse-jdbc-bridge-service` in the same docker-compose file, but got error from the clickhouse-server
```
jdbc-bridge is not running. Please, start it manually (version 19.17.2.4 (official build))
```
It seems the clickhouse-server cann't find the clickhouse-jdbc-bridge service.And how to configure clickhouse-server to looking for the `clickhouse-jdbc-bridge`
